export const channels = {
  appHidePalette: "app:hide-palette",
  appQuit: "app:quit",
  appShowLibrary: "app:show-library",
  appShowOnboarding: "app:show-onboarding",
  diagnosticsLog: "diagnostics:log",
  settingsCheckAccessibility: "settings:check-accessibility",
  settingsGet: "settings:get",
  settingsOpenAccessibility: "settings:open-accessibility-settings",
  settingsUpdate: "settings:update",
  snippetsCreate: "snippets:create",
  snippetsExportDialog: "snippets:export-dialog",
  snippetsImportDialog: "snippets:import-dialog",
  snippetsInsert: "snippets:insert",
  snippetsList: "snippets:list",
  snippetsRemove: "snippets:remove",
  snippetsSearch: "snippets:search",
  snippetsUpdate: "snippets:update",
  eventHotkeyRegistrationFailed: "event:hotkey-registration-failed",
  eventSnippetsChanged: "event:snippets-changed",
} as const;
